import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

import { DashboardConditionalLayout } from "@/components/layout/DashboardConditionalLayout";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({ subsets: ["latin", "vietnamese"], variable: "--font-playfair" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${inter.className} ${inter.variable} ${playfair.variable} min-h-screen flex flex-col bg-slate-50 text-slate-900 antialiased`}>
        <DashboardConditionalLayout>
          {children}
        </DashboardConditionalLayout>
      </body>
    </html>
  );
}
